# Generated by Django 5.2.8 on 2025-11-08 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='solicitante_email',
            field=models.EmailField(default='desconocido@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='solicitante_nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='solicitante_telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadoreserva',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='creada_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservas.estadoreserva'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
