# Generated by Django 5.2.8 on 2025-11-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_motivo_sala_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
